require "initializer"
require "log"

require "constant/constant"
require "constant/constant/module"
require "constant/constant/literal"
require "constant/log"
require "constant/define"
require "constant/import"
require "constant/import/macro"
